alter table public.startups
  add column if not exists yc_batch text,
  add column if not exists yc_url text;

update public.startups
set yc_batch = 'S19',
    yc_url = 'https://www.ycombinator.com/companies/mercury'
where slug = 'mercury';

update public.startups
set yc_batch = 'W09',
    yc_url = 'https://www.ycombinator.com/companies/airbnb'
where slug = 'airbnb';

insert into public.startups (
  id,
  slug,
  name,
  description,
  category,
  amount_raised,
  round_label,
  yc_batch,
  yc_url,
  sort_order,
  is_published,
  website_url,
  source_urls,
  source_summary,
  pattern,
  build_angle,
  target_customer,
  starter_stack,
  enriched_at
)
values
  (
    '55555555-5555-4555-8555-555555555555',
    'stripe',
    'Stripe',
    'Economic infrastructure for online payments, billing, subscriptions, identity, tax, and financial operations.',
    'saas',
    'Private company',
    'YC alumni',
    'S09',
    'https://www.ycombinator.com/companies/stripe',
    30,
    true,
    'https://stripe.com',
    array['https://www.ycombinator.com/companies/stripe', 'https://stripe.com'],
    'YC lists Stripe as a Summer 2009 company building economic infrastructure for the internet.',
    'A developer-first payments platform that turns complex financial workflows into composable APIs and dashboards.',
    'Start with one painful money movement workflow for a narrow merchant type before expanding into billing, tax, and reconciliation.',
    'Operators who need to accept payments, reconcile transactions, and handle edge cases without becoming payments experts.',
    array['Payment links', 'Customer records', 'Webhook events', 'Reconciliation exports', 'Exception handling'],
    now()
  ),
  (
    '66666666-6666-4666-8666-666666666666',
    'dropbox',
    'Dropbox',
    'Cloud file sync, backup, sharing, collaboration, and workspace tools for teams and individuals.',
    'saas',
    'Public company',
    'YC alumni',
    'S07',
    'https://www.ycombinator.com/companies/dropbox',
    40,
    true,
    'https://www.dropbox.com',
    array['https://www.ycombinator.com/companies/dropbox', 'https://www.dropbox.com'],
    'YC lists Dropbox as a Summer 2007 company focused on cloud backup and file sharing.',
    'A dead-simple sync layer that makes files available, shareable, recoverable, and understandable across devices and collaborators.',
    'Niche the file layer around a regulated handoff, approval, or archive workflow where generic folders create risk.',
    'Document-heavy teams that lose time chasing file versions, permissions, signatures, or audit trails.',
    array['Folder templates', 'Version history', 'Permission presets', 'Client upload portal', 'Audit exports'],
    now()
  ),
  (
    '77777777-7777-4777-8777-777777777777',
    'gusto',
    'Gusto',
    'Payroll, benefits, HR, onboarding, compliance, and people operations software for growing businesses.',
    'saas',
    'Private company',
    'YC alumni',
    'W12',
    'https://www.ycombinator.com/companies/gusto',
    50,
    true,
    'https://gusto.com',
    array['https://www.ycombinator.com/companies/gusto', 'https://gusto.com'],
    'YC lists Gusto as a Winter 2012 company providing payroll, benefits, and HR software.',
    'A people-ops system of record that turns payroll compliance and employee administration into repeatable workflows.',
    'Pick one employee-heavy niche with recurring compliance tasks and sell a guided payroll-adjacent operating workflow.',
    'Small business owners and office managers who run payroll and HR from spreadsheets, email, and accountant reminders.',
    array['Employee directory', 'Onboarding checklist', 'Payroll reminders', 'Document vault', 'Compliance calendar'],
    now()
  ),
  (
    '88888888-8888-4888-8888-888888888888',
    'coinbase',
    'Coinbase',
    'Cryptocurrency exchange and wallet platform for buying, selling, storing, and managing digital assets.',
    'marketplace',
    'Public company',
    'YC alumni',
    'S12',
    'https://www.ycombinator.com/companies/coinbase',
    60,
    true,
    'https://www.coinbase.com',
    array['https://www.ycombinator.com/companies/coinbase', 'https://www.coinbase.com'],
    'YC lists Coinbase as a Summer 2012 company for buying, selling, and managing cryptocurrencies.',
    'A trust and custody layer that makes a technically risky asset feel legible enough for mainstream users and institutions.',
    'Apply the custody, education, and transaction-history pattern to one niche asset, compliance, or treasury workflow.',
    'Operators who need to track ownership, approvals, and transaction records for complex digital or financial assets.',
    array['Asset ledger', 'Identity checks', 'Transaction history', 'Policy approvals', 'Monthly statements'],
    now()
  ),
  (
    '99999999-9999-4999-8999-999999999999',
    'instacart',
    'Instacart',
    'Marketplace for grocery delivery and pickup, connecting households, retailers, and personal shoppers.',
    'marketplace',
    'Public company',
    'YC alumni',
    'S12',
    'https://www.ycombinator.com/companies/instacart',
    70,
    true,
    'https://www.instacart.com',
    array['https://www.ycombinator.com/companies/instacart', 'https://www.instacart.com'],
    'YC lists Instacart as a Summer 2012 marketplace for grocery delivery and pickup.',
    'A local fulfillment marketplace that coordinates inventory, substitution decisions, delivery windows, and shopper trust.',
    'Start with one local replenishment workflow where buyers need recurring delivery and suppliers need predictable demand.',
    'Local retailers, service providers, or households that repeatedly coordinate purchases, substitutions, and deliveries by phone.',
    array['Recurring orders', 'Inventory notes', 'Substitution rules', 'Shopper assignments', 'Delivery windows'],
    now()
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    'doordash',
    'DoorDash',
    'Local commerce and restaurant delivery marketplace for ordering, logistics, merchant tools, and last-mile fulfillment.',
    'marketplace',
    'Public company',
    'YC alumni',
    'S13',
    'https://www.ycombinator.com/companies/doordash',
    80,
    true,
    'https://www.doordash.com',
    array['https://www.ycombinator.com/companies/doordash', 'https://www.doordash.com'],
    'YC lists DoorDash as a Summer 2013 company focused on restaurant delivery.',
    'A last-mile logistics network that turns local demand, merchant capacity, couriers, and timing into a coordinated marketplace.',
    'Build for a constrained local vertical where speed, reliability, and repeat ordering matter more than broad selection.',
    'Local merchants that want delivery demand without building dispatch, ordering, and customer communication workflows.',
    array['Merchant menu', 'Order queue', 'Driver dispatch', 'Delivery tracking', 'Customer notifications'],
    now()
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    'gitlab',
    'GitLab',
    'DevOps platform for source control, CI/CD, security, planning, deployment, and software delivery governance.',
    'saas',
    'Public company',
    'YC alumni',
    'W15',
    'https://www.ycombinator.com/companies/gitlab',
    90,
    true,
    'https://gitlab.com',
    array['https://www.ycombinator.com/companies/gitlab', 'https://gitlab.com'],
    'YC lists GitLab as a Winter 2015 company building a complete DevOps platform.',
    'A single workflow surface for code, planning, review, deployment, and compliance across the software lifecycle.',
    'Niche the DevOps lifecycle around one compliance-heavy or non-software technical team that needs handoffs and auditability.',
    'Technical teams that ship regulated changes and need traceability without stitching together many developer tools.',
    array['Issue templates', 'Change approvals', 'Deployment checklist', 'Audit log', 'Release notes'],
    now()
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    'brex',
    'Brex',
    'Business accounts, corporate cards, expense management, bill pay, travel, and spend-control software.',
    'saas',
    'Acquired',
    'YC alumni',
    'W17',
    'https://www.ycombinator.com/companies/brex',
    100,
    true,
    'https://www.brex.com',
    array['https://www.ycombinator.com/companies/brex', 'https://www.brex.com'],
    'YC lists Brex as a Winter 2017 company for business accounts, corporate cards, and spend management.',
    'A founder-friendly financial operating layer that packages cards, controls, approvals, and visibility into one workflow.',
    'Start with spend controls and reporting for one professional niche before adding card issuance or banking primitives.',
    'Teams with frequent card spend, weak approval habits, and a finance owner who needs policy enforcement.',
    array['Virtual cards', 'Spend policies', 'Receipt inbox', 'Approval queue', 'Accounting sync'],
    now()
  ),
  (
    'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
    'retool',
    'Retool',
    'Low-code platform for building internal tools, admin panels, workflows, and AI-powered operational apps.',
    'saas',
    'Private company',
    'YC alumni',
    'W17',
    'https://www.ycombinator.com/companies/retool',
    110,
    true,
    'https://retool.com',
    array['https://www.ycombinator.com/companies/retool', 'https://retool.com'],
    'YC lists Retool as a Winter 2017 company for building internal tools fast.',
    'A fast internal-app builder that connects databases, APIs, permissions, and operational UI into custom workflows.',
    'Ship a pre-opinionated internal tool for one back-office process instead of a general builder.',
    'Operations teams that repeatedly ask engineering for small admin tools, approvals, dashboards, and database edits.',
    array['Data connector', 'Table editor', 'Role permissions', 'Approval actions', 'Activity log'],
    now()
  ),
  (
    'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
    'deel',
    'Deel',
    'Global HR and payroll platform for hiring, onboarding, compliance, benefits, equipment, and workforce operations.',
    'saas',
    'Private company',
    'YC alumni',
    'W19',
    'https://www.ycombinator.com/companies/deel',
    120,
    true,
    'https://www.deel.com',
    array['https://www.ycombinator.com/companies/deel', 'https://www.deel.com'],
    'YC lists Deel as a Winter 2019 company building an all-in-one HR and payroll platform for global teams.',
    'A compliance-heavy workforce operating system that abstracts country-specific hiring, payroll, contracts, and benefits.',
    'Pick one cross-border worker category and sell the workflow, documents, and reminders before building full payroll depth.',
    'Small companies hiring across borders without legal, HR, or finance teams in every jurisdiction.',
    array['Worker profile', 'Contract templates', 'Compliance checklist', 'Payroll reminders', 'Document storage'],
    now()
  )
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    category = excluded.category,
    amount_raised = excluded.amount_raised,
    round_label = excluded.round_label,
    yc_batch = excluded.yc_batch,
    yc_url = excluded.yc_url,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published,
    website_url = excluded.website_url,
    source_urls = excluded.source_urls,
    source_summary = excluded.source_summary,
    pattern = excluded.pattern,
    build_angle = excluded.build_angle,
    target_customer = excluded.target_customer,
    starter_stack = excluded.starter_stack,
    enriched_at = excluded.enriched_at;

insert into public.startup_fork_ideas (
  startup_id,
  title,
  niche,
  sort_order,
  problem,
  why_it_works,
  mvp,
  go_to_market,
  pricing,
  viability_score,
  evidence,
  generation_model,
  generated_at,
  review_status,
  is_published,
  reviewed_at
)
values
  (
    (select id from public.startups where slug = 'stripe'),
    'Payment ops for independent clinics',
    'healthcare payments',
    10,
    'Independent clinics take deposits, handle no-shows, issue refunds, and reconcile insurance-adjacent payments through generic processors.',
    'The workflow is narrow, repeated, and money-sensitive, so buyers value clean receipts, policy defaults, and fewer reconciliation mistakes.',
    'Payment links, saved customer records, refund rules, deposit tracking, and monthly reconciliation exports.',
    'Start with specialty clinics that already charge deposits and sell concierge setup for their first payment policy templates.',
    '$79-$249 per clinic per month plus payment-processing pass-through.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/stripe","snippet":"YC lists Stripe as a Summer 2009 company for economic infrastructure."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'dropbox'),
    'Client file portal for boutique immigration firms',
    'legal document intake',
    10,
    'Immigration firms chase sensitive files across email threads, shared drives, and client text messages.',
    'The niche needs structured intake, missing-document reminders, permission boundaries, and clean handoff packets.',
    'Matter folders, required-document checklists, secure uploads, client reminders, and exportable evidence packets.',
    'Sell to small immigration practices and migrate one active case manually to prove time saved.',
    '$99-$399 per firm per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/dropbox","snippet":"YC lists Dropbox as a Summer 2007 company for cloud backup and file sharing."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'gusto'),
    'Payroll prep for multi-location salons',
    'salon operations',
    10,
    'Salon owners combine schedules, commissions, tips, and contractor payments by hand before every payroll run.',
    'The data already exists, but payroll mistakes are expensive and owners want an operational layer before their accountant gets involved.',
    'Staff profiles, commission rules, tip imports, payroll checklist, and accountant export.',
    'Partner with salon bookkeepers and onboard their first three clients with done-for-you rules setup.',
    '$79-$199 per location per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/gusto","snippet":"YC lists Gusto as a Winter 2012 payroll and HR company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'coinbase'),
    'Asset ledger for collectibles dealers',
    'collectibles inventory',
    10,
    'Dealers track provenance, ownership, payments, and custody across spreadsheets, photos, and messages.',
    'The trust pattern maps well to high-value inventory where history, custody, and transaction records matter.',
    'Asset profiles, provenance notes, transfer history, buyer records, and monthly portfolio reports.',
    'Start with niche dealers who already use spreadsheets and offer a white-glove import of their top inventory.',
    '$49-$199 per dealer per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/coinbase","snippet":"YC lists Coinbase as a Summer 2012 company for buying, selling, and managing cryptocurrencies."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'instacart'),
    'Recurring supply runs for childcare centers',
    'childcare procurement',
    10,
    'Childcare centers reorder snacks, cleaning supplies, craft materials, and emergency items through inconsistent local routines.',
    'The order is recurring, substitutions matter, and center directors care more about reliability than broad marketplace selection.',
    'Approved item lists, recurring orders, substitution preferences, delivery windows, and spend summaries.',
    'Start in one metro area with childcare centers and manually coordinate the first deliveries before automating.',
    '$99-$299 per center per month plus delivery fees.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/instacart","snippet":"YC lists Instacart as a Summer 2012 marketplace for grocery delivery and pickup."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'doordash'),
    'Local delivery dispatch for pharmacies',
    'pharmacy delivery',
    10,
    'Independent pharmacies coordinate urgent local deliveries through phone calls, staff errands, and unreliable courier relationships.',
    'The niche has high repeat demand, narrow geography, compliance concerns, and a strong need for delivery visibility.',
    'Delivery request intake, driver assignment, status texts, delivery proof, and route history.',
    'Sell city by city to independent pharmacies and run dispatch manually at first.',
    '$199-$499 per pharmacy per month plus per-delivery fees.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/doordash","snippet":"YC lists DoorDash as a Summer 2013 restaurant delivery company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'gitlab'),
    'Release compliance for medical-device firmware teams',
    'regulated engineering',
    10,
    'Small firmware teams need traceability from change request to review, test evidence, release notes, and audit records.',
    'Generic devtools require configuration; a vertical workflow can encode the expected compliance path from day one.',
    'Change requests, linked test evidence, approval gates, release packets, and immutable audit exports.',
    'Find small device manufacturers preparing audits and replace their spreadsheet release checklist.',
    '$299-$999 per engineering team per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/gitlab","snippet":"YC lists GitLab as a Winter 2015 complete DevOps platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'brex'),
    'Spend controls for field-service contractors',
    'contractor finance ops',
    10,
    'Field-service teams buy parts, fuel, tools, and emergency supplies with weak receipt capture and messy approvals.',
    'The buyer needs policy enforcement and visibility more than a full enterprise spend platform.',
    'Job-coded cards, receipt capture, manager approvals, vendor budgets, and accounting exports.',
    'Sell to HVAC, plumbing, and electrical operators with five to fifty field workers.',
    '$99-$399 per company per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/brex","snippet":"YC lists Brex as a Winter 2017 company for business accounts, cards, and spend management."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'retool'),
    'Ops console for boutique logistics brokers',
    'logistics back office',
    10,
    'Small logistics brokers stitch together order status, carrier calls, customer updates, and invoice exceptions across generic tools.',
    'They need an internal tool, but not a builder; they need an opinionated console around their daily exception queue.',
    'Shipment table, exception flags, customer update actions, carrier notes, and invoice reconciliation views.',
    'Start with brokers using Airtable or spreadsheets and build their first workflow as a service.',
    '$199-$799 per brokerage per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/retool","snippet":"YC lists Retool as a Winter 2017 company for building internal tools fast."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'deel'),
    'Contractor compliance for indie game studios',
    'global contractor ops',
    10,
    'Indie game studios hire artists, composers, writers, and contractors across countries with inconsistent contracts and tax paperwork.',
    'The global hiring workflow is painful, but this niche can start with documents, reminders, and contractor records before payroll complexity.',
    'Contractor profiles, template agreements, tax-document checklist, payment reminders, and project-based access logs.',
    'Sell through game-studio communities and offer a one-time cleanup of existing contractor paperwork.',
    '$79-$249 per studio per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/deel","snippet":"YC lists Deel as a Winter 2019 global HR and payroll company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  )
on conflict (startup_id, title) do update
set niche = excluded.niche,
    sort_order = excluded.sort_order,
    problem = excluded.problem,
    why_it_works = excluded.why_it_works,
    mvp = excluded.mvp,
    go_to_market = excluded.go_to_market,
    pricing = excluded.pricing,
    viability_score = excluded.viability_score,
    evidence = excluded.evidence,
    generation_model = excluded.generation_model,
    generated_at = excluded.generated_at,
    review_status = excluded.review_status,
    is_published = excluded.is_published,
    reviewed_at = excluded.reviewed_at;
