alter table public.startups
  add column if not exists yc_batch text,
  add column if not exists yc_url text;

insert into public.startups (
  slug,
  name,
  description,
  category,
  amount_raised,
  round_label,
  yc_batch,
  yc_url,
  sort_order,
  is_published,
  website_url,
  source_urls,
  source_summary,
  pattern,
  build_angle,
  target_customer,
  starter_stack,
  enriched_at
)
values
  (
    'zapier',
    'Zapier',
    'Workflow automation platform that connects business apps, triggers actions, and moves data between tools.',
    'saas',
    'Private company',
    'YC alumni',
    'S12',
    'https://www.ycombinator.com/companies/zapier',
    130,
    true,
    'https://zapier.com',
    array['https://www.ycombinator.com/companies/zapier', 'https://zapier.com'],
    'YC lists Zapier as a Summer 2012 company for automating work across business apps.',
    'A no-code automation layer that turns repeated cross-app handoffs into triggers, actions, and reusable workflows.',
    'Start with one recurring handoff in a narrow industry, then ship prebuilt automations instead of a general automation canvas.',
    'Small teams that copy data between apps, send routine updates, and need fewer manual admin loops.',
    array['Trigger templates', 'App connectors', 'Approval steps', 'Failure alerts', 'Run history'],
    now()
  ),
  (
    'segment',
    'Segment',
    'Customer data infrastructure for collecting events, cleaning user data, and routing it to analytics and marketing tools.',
    'saas',
    'Acquired',
    'YC alumni',
    'S11',
    'https://www.ycombinator.com/companies/segment',
    140,
    true,
    'https://segment.com',
    array['https://www.ycombinator.com/companies/segment', 'https://segment.com'],
    'YC lists Segment as a Summer 2011 company for customer data collection, cleaning, and routing.',
    'A customer-data control plane that normalizes events once and sends trustworthy data into many downstream tools.',
    'Pick one vertical analytics schema and make the data model, QA checks, and reporting destinations opinionated.',
    'Operators who know their customer data is messy but do not have a data engineering team.',
    array['Event schema', 'Data quality checks', 'Destination routing', 'Identity merge', 'Audit logs'],
    now()
  ),
  (
    'amplitude',
    'Amplitude',
    'Digital analytics platform for product usage, funnels, experiments, cohorts, session replay, and retention insights.',
    'saas',
    'Public company',
    'YC alumni',
    'W12',
    'https://www.ycombinator.com/companies/amplitude',
    150,
    true,
    'https://amplitude.com',
    array['https://www.ycombinator.com/companies/amplitude', 'https://amplitude.com'],
    'YC lists Amplitude as a Winter 2012 digital analytics company.',
    'A product analytics system that translates behavioral events into funnels, retention loops, cohorts, and product decisions.',
    'Replace the generic analytics workspace with one vertical dashboard that knows the key activation, retention, and revenue events.',
    'Product-led teams in a niche market that need answers from usage data without hiring an analyst.',
    array['Event tracker', 'Activation funnel', 'Retention cohorts', 'Experiment notes', 'Weekly insight email'],
    now()
  ),
  (
    'webflow',
    'Webflow',
    'No-code visual website design, CMS, hosting, publishing, and marketing-site operations platform.',
    'saas',
    'Private company',
    'YC alumni',
    'S13',
    'https://www.ycombinator.com/companies/webflow',
    160,
    true,
    'https://webflow.com',
    array['https://www.ycombinator.com/companies/webflow', 'https://webflow.com'],
    'YC lists Webflow as a Summer 2013 company for professional website design and publishing.',
    'A visual web-building platform that combines design, CMS, hosting, and publishing workflows for non-engineering teams.',
    'Build a website workflow for one regulated or template-heavy niche where content, approvals, and launches repeat.',
    'Small marketing teams and agencies that need polished sites but cannot wait on custom engineering for every change.',
    array['Page templates', 'CMS collections', 'Approval workflow', 'Publishing checklist', 'SEO defaults'],
    now()
  ),
  (
    'flexport',
    'Flexport',
    'Global logistics platform for freight forwarding, supply-chain visibility, customs coordination, and shipment management.',
    'saas',
    'Private company',
    'YC alumni',
    'W14',
    'https://www.ycombinator.com/companies/flexport',
    170,
    true,
    'https://www.flexport.com',
    array['https://www.ycombinator.com/companies/flexport', 'https://www.flexport.com'],
    'YC lists Flexport as a Winter 2014 company building a platform for global logistics.',
    'A logistics operating system that makes fragmented freight, customs, documents, and shipment status visible in one workflow.',
    'Start with one shipment-heavy niche and solve document collection, status updates, and exception handling before full freight depth.',
    'Importers, wholesalers, and operators coordinating shipments through email, spreadsheets, and freight-forwarder portals.',
    array['Shipment tracker', 'Document checklist', 'Exception queue', 'Vendor updates', 'Arrival reports'],
    now()
  ),
  (
    'rippling',
    'Rippling',
    'Workforce platform for HR, IT, payroll, benefits, devices, identity, expenses, and employee lifecycle automation.',
    'saas',
    'Private company',
    'YC alumni',
    'W17',
    'https://www.ycombinator.com/companies/rippling',
    180,
    true,
    'https://rippling.com',
    array['https://www.ycombinator.com/companies/rippling', 'https://rippling.com'],
    'YC lists Rippling as a Winter 2017 company for running HR, IT, and finance workflows globally.',
    'An employee lifecycle system that connects people data to payroll, apps, devices, permissions, and operational tasks.',
    'Choose one workforce niche and automate the onboarding/offboarding checklist with the exact tools and compliance tasks they use.',
    'People operators and founders who manually coordinate payroll, access, devices, documents, and expense setup.',
    array['Employee profile', 'Onboarding tasks', 'App access checklist', 'Device tracker', 'Offboarding workflow'],
    now()
  ),
  (
    'scale-ai',
    'Scale AI',
    'Data infrastructure for AI model development, data labeling, evaluation, RLHF, and enterprise AI workflows.',
    'ai',
    'Private company',
    'YC alumni',
    'S16',
    'https://www.ycombinator.com/companies/scale-ai',
    190,
    true,
    'https://scale.com',
    array['https://www.ycombinator.com/companies/scale-ai', 'https://scale.com'],
    'YC lists Scale AI as a Summer 2016 company building data-centric infrastructure for AI.',
    'A data operations layer that turns messy human judgment, labeling, review, and model evaluation into repeatable pipelines.',
    'Niche down to one domain where expert review matters more than raw label volume and sell the workflow around quality control.',
    'Teams building AI features that need labeled examples, evaluation sets, and expert feedback but cannot run a data-ops team.',
    array['Dataset intake', 'Review queue', 'Expert labels', 'Evaluation set', 'Quality dashboard'],
    now()
  ),
  (
    'faire',
    'Faire',
    'Wholesale marketplace connecting independent retailers with brands, inventory discovery, ordering, financing, and analytics.',
    'marketplace',
    'Private company',
    'YC alumni',
    'W17',
    'https://www.ycombinator.com/companies/faire',
    200,
    true,
    'https://www.faire.com',
    array['https://www.ycombinator.com/companies/faire', 'https://www.faire.com'],
    'YC lists Faire as a Winter 2017 marketplace for independent retail and brands.',
    'A B2B marketplace that matches local retailers with fitting brands while reducing inventory risk and simplifying wholesale orders.',
    'Pick one retail category where discovery, minimum orders, reorders, and terms are painful, then curate supply manually first.',
    'Independent shop owners and small brands that rely on trade shows, email, and risky inventory bets.',
    array['Brand directory', 'Retailer profiles', 'Sample requests', 'Reorder reminders', 'Terms tracking'],
    now()
  ),
  (
    'whatnot',
    'Whatnot',
    'Livestream shopping marketplace for collectibles, fashion, trading cards, comics, sneakers, and real-time seller auctions.',
    'marketplace',
    'Private company',
    'YC alumni',
    'W20',
    'https://www.ycombinator.com/companies/whatnot',
    210,
    true,
    'https://www.whatnot.com',
    array['https://www.ycombinator.com/companies/whatnot', 'https://www.whatnot.com'],
    'YC lists Whatnot as a Winter 2020 livestream shopping marketplace.',
    'A live commerce marketplace that combines entertainment, trust, bidding, inventory, shipping, and community around niche goods.',
    'Start with one collector community and provide hosted live drops, seller tools, and buyer trust before broad marketplace features.',
    'Niche sellers who already have social audiences but struggle to convert live attention into reliable commerce.',
    array['Live listings', 'Seller schedule', 'Bidding flow', 'Buyer verification', 'Shipping labels'],
    now()
  ),
  (
    'heroku',
    'Heroku',
    'Cloud platform for building, deploying, scaling, logging, and operating applications without managing infrastructure.',
    'saas',
    'Acquired',
    'YC alumni',
    'W08',
    'https://www.ycombinator.com/companies/heroku',
    220,
    true,
    'https://www.heroku.com',
    array['https://www.ycombinator.com/companies/heroku', 'https://www.heroku.com'],
    'YC lists Heroku as a Winter 2008 company for building and running applications in the cloud.',
    'A developer platform that hides infrastructure behind simple deploys, managed add-ons, logs, scaling, and operational defaults.',
    'Create a deploy-and-operate workflow for one narrow app type where users want working software, logs, and backups without DevOps.',
    'Technical founders and agencies shipping small production apps without a dedicated infrastructure owner.',
    array['Git deploy', 'Environment variables', 'Managed database', 'Log stream', 'Backup schedule'],
    now()
  )
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    category = excluded.category,
    amount_raised = excluded.amount_raised,
    round_label = excluded.round_label,
    yc_batch = excluded.yc_batch,
    yc_url = excluded.yc_url,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published,
    website_url = excluded.website_url,
    source_urls = excluded.source_urls,
    source_summary = excluded.source_summary,
    pattern = excluded.pattern,
    build_angle = excluded.build_angle,
    target_customer = excluded.target_customer,
    starter_stack = excluded.starter_stack,
    enriched_at = excluded.enriched_at;

insert into public.startup_fork_ideas (
  startup_id,
  title,
  niche,
  sort_order,
  problem,
  why_it_works,
  mvp,
  go_to_market,
  pricing,
  viability_score,
  evidence,
  generation_model,
  generated_at,
  review_status,
  is_published,
  reviewed_at
)
values
  (
    (select id from public.startups where slug = 'zapier'),
    'Automation playbooks for boutique property managers',
    'property management ops',
    10,
    'Small property managers repeatedly move tenant, maintenance, rent, and owner-update data between inboxes, spreadsheets, portals, and accounting tools.',
    'The job is mostly recurring coordination, so prebuilt automations for one property workflow beat a blank automation builder.',
    'Maintenance intake triggers, owner update templates, rent reminder workflows, vendor assignment rules, and failure alerts.',
    'Sell through property manager communities and set up the first five automations manually during onboarding.',
    '$99-$299 per property manager per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/zapier","snippet":"YC lists Zapier as a Summer 2012 workflow automation company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'segment'),
    'Customer data QA for Shopify agencies',
    'ecommerce analytics',
    10,
    'Ecommerce teams launch tracking tags and marketing events that silently break, duplicate, or mismatch ad-platform expectations.',
    'A vertical schema and automated QA checks are more valuable than a generic CDP for teams that mainly need trustworthy campaign data.',
    'Prebuilt ecommerce event schema, duplicate detection, checkout-event monitor, destination checks, and weekly data-health reports.',
    'Partner with Shopify agencies and audit tracking for one client as the wedge.',
    '$149-$499 per store per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/segment","snippet":"YC lists Segment as a Summer 2011 customer data infrastructure company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'amplitude'),
    'Retention analytics for cohort-based course creators',
    'creator education',
    10,
    'Course creators know signups and revenue, but not which lessons, reminders, or community actions predict completion and renewals.',
    'The analytics questions are repetitive and domain-specific, so the product can ship with the right funnels already named.',
    'Lesson engagement tracking, cohort retention chart, completion funnel, churn-risk list, and weekly improvement suggestions.',
    'Start with high-ticket cohort programs and install tracking as a done-for-you onboarding service.',
    '$99-$399 per course per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/amplitude","snippet":"YC lists Amplitude as a Winter 2012 digital analytics platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'webflow'),
    'Website builder for independent medical spas',
    'local healthcare marketing',
    10,
    'Medical spas need compliant service pages, before-and-after policies, promos, booking links, and frequent local SEO updates.',
    'A niche builder can include the right page types, approval steps, and content defaults instead of asking owners to design from scratch.',
    'Service-page templates, promo landing pages, booking embeds, compliance checklist, and local SEO content blocks.',
    'Sell to med spa consultants and rebuild one underperforming site as a fixed-price onboarding package.',
    '$129-$399 per location per month plus setup.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/webflow","snippet":"YC lists Webflow as a Summer 2013 professional website design and publishing platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'flexport'),
    'Import tracker for specialty food distributors',
    'food supply chain',
    10,
    'Specialty food distributors coordinate import documents, temperature requirements, customs status, arrival dates, and retailer expectations in scattered threads.',
    'The niche has high document density and expensive delays, but the MVP can start as visibility and exception management.',
    'Shipment board, document checklist, temperature notes, arrival alerts, customs status, and retailer update emails.',
    'Find distributors importing perishable goods and manually migrate active shipments from spreadsheets.',
    '$249-$799 per distributor per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/flexport","snippet":"YC lists Flexport as a Winter 2014 global logistics platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'rippling'),
    'Onboarding automation for dental groups',
    'healthcare workforce ops',
    10,
    'Dental groups onboard hygienists, assistants, front-desk staff, and contractors with licenses, systems access, uniforms, payroll, and clinic-specific checklists.',
    'The employee lifecycle is repeatable and compliance-heavy, so a narrow checklist product can feel complete without becoming a full HRIS.',
    'Role templates, license checklist, payroll handoff, systems-access tasks, equipment tracker, and offboarding workflow.',
    'Sell to growing dental groups opening new locations and offer template setup per role.',
    '$149-$499 per group per month.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/rippling","snippet":"YC lists Rippling as a Winter 2017 HR, IT, and finance workforce platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'scale-ai'),
    'Expert review queue for legal AI tools',
    'legal AI evaluation',
    10,
    'Legal AI teams need attorneys to review model outputs, rate risk, capture edge cases, and build evaluation sets without messy spreadsheets.',
    'The wedge is quality control and expert workflow, not generic data labeling, which makes it easier to sell into a narrow compliance-sensitive buyer.',
    'Matter-type dataset intake, attorney review queue, rubric scoring, issue tagging, and model-evaluation exports.',
    'Start with legal AI startups and boutique firms piloting document automation.',
    '$499-$1,500 per month plus expert review seats.',
    5,
    $$[{"source":"https://www.ycombinator.com/companies/scale-ai","snippet":"YC lists Scale AI as a Summer 2016 data-centric AI infrastructure company."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'faire'),
    'Wholesale marketplace for independent garden centers',
    'garden retail',
    10,
    'Garden centers discover local suppliers, seasonal inventory, pots, tools, and decor through phone calls, trade shows, and risky minimum orders.',
    'The market has repeat seasonal buying, fragmented suppliers, and clear curation needs, making a narrower B2B marketplace plausible.',
    'Supplier profiles, seasonal catalogs, sample requests, reorder reminders, and payment-terms tracker.',
    'Start with one region and onboard suppliers manually before adding ordering automation.',
    '$99-$299 per retailer per month plus supplier success fees.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/faire","snippet":"YC lists Faire as a Winter 2017 marketplace for independent retail."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'whatnot'),
    'Live auction platform for local estate sellers',
    'estate sale commerce',
    10,
    'Estate sellers already create urgency and trust in person, but online selling requires livestreaming, bidding, payments, shipping, and buyer confidence.',
    'The live commerce loop works well where inventory is scarce, visual, and story-driven.',
    'Scheduled live drops, item queue, bidding, buyer verification, invoice collection, and shipping labels.',
    'Pilot with estate-sale operators who already have email lists and social followings.',
    '$99-$399 per seller per month plus transaction fees.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/whatnot","snippet":"YC lists Whatnot as a Winter 2020 livestream shopping marketplace."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  ),
  (
    (select id from public.startups where slug = 'heroku'),
    'One-click hosting for local agency maintenance sites',
    'agency devops',
    10,
    'Small agencies host many low-complexity client apps and struggle with environment variables, logs, backups, updates, and client-specific handoffs.',
    'A constrained platform can remove DevOps decisions for a repeated app type and charge for operational calm.',
    'Git deploy, managed database, env var vault, uptime monitor, backup schedule, and client handoff dashboard.',
    'Sell to agencies maintaining five to fifty small production apps and migrate one app manually.',
    '$19-$79 per app per month.',
    4,
    $$[{"source":"https://www.ycombinator.com/companies/heroku","snippet":"YC lists Heroku as a Winter 2008 cloud application platform."}]$$::jsonb,
    'manual-yc-seed',
    now(),
    'approved',
    true,
    now()
  )
on conflict (startup_id, title) do update
set niche = excluded.niche,
    sort_order = excluded.sort_order,
    problem = excluded.problem,
    why_it_works = excluded.why_it_works,
    mvp = excluded.mvp,
    go_to_market = excluded.go_to_market,
    pricing = excluded.pricing,
    viability_score = excluded.viability_score,
    evidence = excluded.evidence,
    generation_model = excluded.generation_model,
    generated_at = excluded.generated_at,
    review_status = excluded.review_status,
    is_published = excluded.is_published,
    reviewed_at = excluded.reviewed_at;
